CREATE TABLE CATEGORY (
                          CATEGORY_ID NUMBER,
                          CATEGORY_NAME VARCHAR2(50) NOT NULL,
                          DESCRIPTION VARCHAR2(200),
                          CONSTRAINT PK_CATEGORY
                              PRIMARY KEY (CATEGORY_ID),
                          CONSTRAINT UQ_CATEGORY_NAME
                              UNIQUE (CATEGORY_NAME)
);


CREATE TABLE SUPPLIER (
                          SUPPLIER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          SUPPLIER_NAME VARCHAR2(100) NOT NULL,
                          PHONE VARCHAR2(15),
                          EMAIL VARCHAR2(100),
                          ADDRESS VARCHAR2(250),
                          CONSTRAINT PK_SUPPLIER
                              PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE PRODUCT (
                         PRODUCT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                         PRODUCT_NAME VARCHAR2(100) NOT NULL,
                         DESCRIPTION VARCHAR2(500),
                         CATEGORY_ID NUMBER NOT NULL,
                         SUPPLIER_ID NUMBER NOT NULL,
                         PRICE NUMBER(10,2) NOT NULL,
                         QUANTITY NUMBER DEFAULT 0 NOT NULL,
                         REORDER_LEVEL NUMBER DEFAULT 5 NOT NULL,
                         STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
                         CONSTRAINT PK_PRODUCT
                             PRIMARY KEY (PRODUCT_ID),
                         CONSTRAINT FK_PRODUCT_CATEGORY
                             FOREIGN KEY (CATEGORY_ID)
                                 REFERENCES CATEGORY(CATEGORY_ID),
                         CONSTRAINT FK_PRODUCT_SUPPLIER
                             FOREIGN KEY (SUPPLIER_ID)
                                 REFERENCES SUPPLIER(SUPPLIER_ID),
                         CONSTRAINT CHK_PRODUCT_PRICE
                             CHECK (PRICE > 0),
                         CONSTRAINT CHK_PRODUCT_QUANTITY
                             CHECK (QUANTITY >= 0),
                         CONSTRAINT CHK_PRODUCT_REORDER
                             CHECK (REORDER_LEVEL >= 0),
                         CONSTRAINT CHK_PRODUCT_STATUS
                             CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);